#!/bin/bash

set -e

source lib.sh

MASKED_EMAIL_ID=$1

BEARER=$(cat ./.env/token)
API_URL="https://api.fastmail.com/jmap/api"
ACCOUNT_ID=$(get_session_token $BEARER)
echo $BEARER $ACCOUNT_ID $MASKED_EMAIL_ID
#MASKED_EMAILS=$(destroy_masked_email $BEARER $ACCOUNT_ID $MASKED_EMAIL_ID)
echo $MASKED_EMAILS
